# Generated by Django 6.0.6 on 2026-07-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantScopedManager',
        ),
        migrations.AlterModelManagers(
            name='idempotencykey',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
            ],
        ),
    ]
