# Generated by Django 6.0.6 on 2026-07-13 14:26

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_idempotencykey_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantScopedQuerySet',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'base_manager_name': 'unscoped_objects'},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='idempotencykey',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
