# Generated by Django 6.0.6 on 2026-07-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdrawal'), ('TRANSFER', 'Transfer')], max_length=15),
        ),
    ]
