#====================================================================================#
#----------------------  Wallet API Tests Generated by Gemini ------------------------#
#====================================================================================#
import uuid
import threading
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.test import TransactionTestCase 
from django.db import connection
from rest_framework import status  # type:ignore

from wallets.models import Tenant, Customer, Wallet, Transaction, IdempotencyKey
from wallets.services import WalletService
from wallets.exceptions import InsufficientFundsError, CrossTenantOperationError, WalletNotFoundError

class WalletAPITests(TransactionTestCase):

    def setUp(self):
        """
        Setup core tenant workspaces, auth user objects, and target customer profiles.
        """
        # Create Tenants
        self.tenant_a = Tenant.objects.create(id=uuid.uuid4(), name="Tenant Alpha Workspace")
        self.tenant_b = Tenant.objects.create(id=uuid.uuid4(), name="Tenant Beta Workspace")

        # Distinct users to satisfy unique constraints
        self.user_a1 = User.objects.create_user(username="alice_alpha", password="password123")
        self.user_a2 = User.objects.create_user(username="charlie_alpha", password="password123")
        self.user_b = User.objects.create_user(username="bob_beta", password="password123")

        # Customer records
        self.customer_a1 = Customer.objects.create(tenant=self.tenant_a, user=self.user_a1)
        self.customer_a2 = Customer.objects.create(tenant=self.tenant_a, user=self.user_a2)
        self.customer_b = Customer.objects.create(tenant=self.tenant_b, user=self.user_b)

        # Distinct wallets matching UNIQUE validation constraints
        self.wallet_a1 = Wallet.objects.create(tenant=self.tenant_a, customer=self.customer_a1, currency="USD")
        self.wallet_a2 = Wallet.objects.create(tenant=self.tenant_a, customer=self.customer_a2, currency="USD")
        self.wallet_b = Wallet.objects.create(tenant=self.tenant_b, customer=self.customer_b, currency="USD")

        # Standard Endpoint URL Reverse Mapping
        self.deposit_url_a1 = f"/api/wallets/{self.wallet_a1.id}/deposit/"
        self.withdraw_url_a1 = f"/api/wallets/{self.wallet_a1.id}/withdraw/"
        self.transfer_url_a1 = f"/api/wallets/{self.wallet_a1.id}/transfer/"

    # ==========================================
    # 1. CORE TRANSACTION & BUSINESS LOGIC
    # ==========================================
    def test_withdrawal_fails_with_insufficient_funds(self):
        """Ensures service/view layer catches insufficient balance conditions safely."""
        WalletService.deposit(tenant_id=self.tenant_a.id, wallet_id=str(self.wallet_a1.id), amount=5000)
        response = self.client.post(
            self.withdraw_url_a1, 
            data={"amount": 6000}, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_deposit_negative_amount_raises_validation_error(self):
        """Ensures passing <= 0 minor units throws a clean ValueError."""
        with self.assertRaises(ValueError):
            WalletService.deposit(tenant_id=self.tenant_a.id, wallet_id=str(self.wallet_a1.id), amount=-500)

    def test_transfer_same_wallet_fails(self):
        """Ensures transferring to oneself is blocked at the service level."""
        with self.assertRaises(ValueError):
            WalletService.transfer(
                tenant_id=self.tenant_a.id, 
                sender_wallet_id=str(self.wallet_a1.id), 
                recipient_wallet_id=str(self.wallet_a1.id), 
                amount=100
            )

    # ==========================================
    # 2. ADVANCED CONCURRENCY & IDEMPOTENCY
    # ==========================================
    def test_duplicate_idempotency_key_cached_response(self):
        """Verifies duplicate requests with identical idempotency headers return identical cached payloads."""
        idem_key = str(uuid.uuid4())
        payload = {"amount": 2500}
        headers = {
            'HTTP_X_TENANT_ID': str(self.tenant_a.id),
            'HTTP_IDEMPOTENCY_KEY': idem_key
        }

        response1 = self.client.post(self.deposit_url_a1, data=payload, content_type='application/json', **headers)
        self.assertEqual(response1.status_code, status.HTTP_201_CREATED)

        response2 = self.client.post(self.deposit_url_a1, data=payload, content_type='application/json', **headers)
        self.assertEqual(response2.status_code, status.HTTP_201_CREATED)
        
        # Comparing decoded JSON HTTP response bodies ensures standard string types match
        self.assertEqual(response1.json(), response2.json())

    def test_concurrent_transfers_race_handling(self):
        """Spawns concurrent worker threads executing transfers simultaneously to ensure balance safety."""
        WalletService.deposit(tenant_id=self.tenant_a.id, wallet_id=str(self.wallet_a1.id), amount=10000)

        exceptions = []
        payload = {"to_wallet_id": str(self.wallet_a2.id), "amount": 6000}

        def threaded_transfer():
            connection.close()  # Force thread to open its own DB connection
            try:
                response = self.client.post(
                    self.transfer_url_a1, 
                    data=payload, 
                    content_type='application/json', 
                    HTTP_X_TENANT_ID=str(self.tenant_a.id)
                )
                if response.status_code >= 400:
                    exceptions.append(response.data)
            except Exception as e:
                exceptions.append(e)

        thread1 = threading.Thread(target=threaded_transfer)
        thread2 = threading.Thread(target=threaded_transfer)

        thread1.start()
        thread2.start()
        thread1.join()
        thread2.join()

        self.assertTrue(len(exceptions) >= 1, "Concurrency protection failed to intercept double-spend!")
        self.wallet_a1.refresh_from_db()
        self.assertIn(self.wallet_a1.balance, [4000, 10000])

    # ==========================================
    # 3. TENANT ISOLATION & MIDDLEWARE GUARDRAILS
    # ==========================================
    def test_cross_tenant_access_blocked(self):
        """Verifies that requests cannot access database records bound to other tenant domains."""
        cross_deposit_url = f"/api/wallets/{self.wallet_b.id}/deposit/"
        response = self.client.post(
            cross_deposit_url, 
            data={"amount": 1000}, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_request_missing_tenant_header_fails(self):
        """Ensures the API completely rejects requests lacking a tracking tenant context header."""
        response = self.client.post(self.deposit_url_a1, data={"amount": 1000}, content_type='application/json')
        self.assertEqual(response.status_code, 400)

    # ==========================================
    # 4. EXPLICIT REST CRUD AND QUERY COVERAGE
    # ==========================================
    def test_tenant_viewset_crud(self):
        """Covers all default model viewset routes inside TenantViewSet."""
        response = self.client.get('/api/tenants/', HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response.status_code, 200)

        response = self.client.post(
            '/api/tenants/', 
            data={"id": str(uuid.uuid4()), "name": "New Tenant"}, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 201)

    def test_customer_creation_appends_middleware_tenant(self):
        """Covers perform_create inside CustomerViewSet to ensure tenant context binds automatically."""
        new_user = User.objects.create_user(
            username="new_customer_user", password="password123"
        )
        payload = {"user": new_user.id, "email": "new_customer@tenant.com"}
        response = self.client.post(
            "/api/customers/",
            data=payload,
            content_type="application/json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id),
        )
        self.assertEqual(response.status_code, 201)
        self.assertEqual(
            str(Customer.objects.get(id=response.data["id"]).tenant_id),
            str(self.tenant_a.id),
        )

    def test_wallet_creation_appends_middleware_tenant(self):
        """Covers perform_create inside WalletViewSet."""
        payload = {"customer": str(self.customer_a2.id), "currency": "EUR"}
        response = self.client.post(
            '/api/wallets/', 
            data=payload, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 201)

    def test_read_only_viewsets_querysets(self):
        """Covers standard list paths for Transaction and Idempotency key tracking viewsets."""
        self.client.get('/api/transactions/', HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.client.get('/api/idempotency-keys/', HTTP_X_TENANT_ID=str(self.tenant_a.id))

    def test_wallet_history_pagination_and_branches(self):
        """Covers live_balance calculations, listing history, and standard output loops inside views."""
        WalletService.deposit(tenant_id=self.tenant_a.id, wallet_id=str(self.wallet_a1.id), amount=1000)
        url = f"/api/wallets/{self.wallet_a1.id}/history/"
        response = self.client.get(url, HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response.status_code, 200)
        self.assertIn('live_balance', response.data)

    # ==========================================
    # 5. ERROR PATTERN AND EXCEPTION COVERAGE
    # ==========================================
    def test_custom_exceptions_payload_and_mapping(self):
        """Verify custom domain exceptions map to the correct error structures and HTTP statuses."""
        from wallets.exceptions import custom_wallet_exception_handler
        
        exc_1 = InsufficientFundsError("Not enough cash.")
        res_1 = custom_wallet_exception_handler(exc_1, {})
        self.assertEqual(res_1.status_code, 422)
        self.assertEqual(res_1.data['error']['code'], 'insufficient_funds')

        exc_2 = CrossTenantOperationError()
        res_2 = custom_wallet_exception_handler(exc_2, {})
        self.assertEqual(res_2.status_code, 403)

    def test_customer_overall_history_not_found(self):
        """Force views.py to execute the customer overall-history exception catch block."""
        bad_uuid = uuid.uuid4()
        url = f"/api/customers/{bad_uuid}/overall-history/"
        response = self.client.get(url, HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response.status_code, 404)

    def test_wallet_history_not_found(self):
        """Force views.py to execute the wallet history exception catch block."""
        bad_uuid = uuid.uuid4()
        url = f"/api/wallets/{bad_uuid}/history/"
        response = self.client.get(url, HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response.status_code, 404)

    def test_wallet_deposit_validation_error_catch(self):
        """Send bad data to verify the service exception capturing logic in view endpoints."""
        url = f"/api/wallets/{self.wallet_a1.id}/deposit/"
        response = self.client.post(
            url, 
            data={"amount": -50}, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_wallet_withdraw_validation_error_catch(self):
        """Send an excessive amount to trigger a validation error inside the withdraw view."""
        url = f"/api/wallets/{self.wallet_a1.id}/withdraw/"
        response = self.client.post(
            url, 
            data={"amount": 99999999}, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_wallet_transfer_validation_error_catch(self):
        """Trigger a validation catch block by attempting to run a self-transfer through the view endpoint."""
        url = f"/api/wallets/{self.wallet_a1.id}/transfer/"
        payload = {"to_wallet_id": str(self.wallet_a1.id), "amount": 500}
        response = self.client.post(
            url, 
            data=payload, 
            content_type='application/json', 
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_staff_user_unscoped_querysets(self):
        """Authenticate a staff user and call '?all=true' query parameters across your Viewsets."""
        staff_user = User.objects.create_user(username="staff_admin", password="password123", is_staff=True)
        self.client.force_login(staff_user)

        response_cust = self.client.get("/api/customers/?all=true", HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response_cust.status_code, 200)

        response_wallet = self.client.get("/api/wallets/?all=true", HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response_wallet.status_code, 200)

        url_hist = f"/api/customers/{self.customer_a1.id}/overall-history/?all=true"
        response_hist = self.client.get(url_hist, HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.assertEqual(response_hist.status_code, 200)

        self.client.get("/api/transactions/?all=true", HTTP_X_TENANT_ID=str(self.tenant_a.id))
        self.client.get("/api/idempotency-keys/?all=true", HTTP_X_TENANT_ID=str(self.tenant_a.id))

        self.client.logout()