# Generated by Django 6.0.6 on 2026-06-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gym Companies',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='gyms.classbooking')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE_REQUIRED', 'Needs Repair'), ('BROKEN', 'Out of Order')], default='OPERATIONAL', max_length=30)),
                ('last_inspected_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gyms.branch')),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_overview', models.TextField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gyms.branch')),
            ],
            options={
                'verbose_name_plural': 'Gym Classes',
            },
        ),
        migrations.AddField(
            model_name='classbooking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gyms.gymclass'),
        ),
        migrations.AddField(
            model_name='branch',
            name='gym_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='gyms.gymcompany'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('gym_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gymcompany')),
            ],
        ),
        migrations.AddField(
            model_name='classbooking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='gyms.member'),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=100)),
                ('ratings', models.FloatField(default=0.0)),
                ('branch', models.ManyToManyField(related_name='trainers', to='gyms.branch')),
            ],
        ),
        migrations.AddField(
            model_name='gymclass',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='gyms.trainer'),
        ),
        migrations.CreateModel(
            name='TrainerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_bonus_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bank_account_info', models.CharField(max_length=100)),
                ('gym_compnay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_payrolls', to='gyms.gymcompany')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_record', to='gyms.trainer')),
            ],
            options={
                'verbose_name_plural': 'Trainer Salaries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('member', 'gym_class')},
        ),
    ]
