# Generated by Django 6.0.6 on 2026-06-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainersalary',
            old_name='gym_compnay',
            new_name='gym_company',
        ),
    ]
