# Generated by Django 6.0.6 on 2026-06-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.member')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='operations.classbooking')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('BROKEN', 'Out of Order')], default='OPERATIONAL', max_length=30)),
                ('last_inspected_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='companies.branch')),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(db_index=True, max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='companies.branch')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='users.trainer')),
            ],
            options={
                'verbose_name_plural': 'Gym Classes',
            },
        ),
        migrations.AddField(
            model_name='classbooking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='operations.gymclass'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('member', 'gym_class')},
        ),
    ]
