# Generated by Django 6.0.6 on 2026-06-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentasset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
