# Generated by Django 6.0.6 on 2026-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_equipmentasset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentasset',
            name='condition_status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE_REQUIRED', 'Needs Repair'), ('BROKEN', 'Out of Order')], default='OPERATIONAL', max_length=30),
        ),
    ]
