# Generated by Django 6.0.5 on 2026-06-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Task Title')),
                ('description', models.TextField(blank=True, help_text='Add detailed note', null=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completed?')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='H', max_length=1)),
                ('category', models.CharField(default='General', help_text='Prayer, Work, Gym, Personal', max_length=50)),
            ],
            options={
                'verbose_name': 'Todo Apps',
                'verbose_name_plural': 'Todo Apps',
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
