# Generated by Django 6.0.5 on 2026-06-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('1_High', 'High'), ('2_Medium', 'Medium'), ('3_Low', 'Low')], default='H', max_length=10),
        ),
    ]
