# Generated by Django 6.0.5 on 2026-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todoitem_options_todoitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['is_completed', 'priority', 'due_date'], 'verbose_name': 'Todo Apps', 'verbose_name_plural': 'Todo Apps'},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
