# Generated by Django 6.0.5 on 2026-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todoitem_options_alter_todoitem_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='task_owner',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Task Owner'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Task Title'),
        ),
    ]
