# Generated by Django 6.0.5 on 2026-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todoitem_task_owner_alter_todoitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task_owner',
            field=models.CharField(max_length=100, verbose_name='Task Owner'),
        ),
    ]
