# Generated by Django 6.0.6 on 2026-06-27 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('speciality', models.CharField(db_index=True, max_length=100)),
                ('ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('branches', models.ManyToManyField(related_name='trainers', to='companies.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.branch')),
                ('gym_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.gymcompany')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('gym_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_salaries', to='companies.gymcompany')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='users.trainer')),
            ],
        ),
    ]
